baseURL = 'https://ivanmolinamas.github.io/web-practica-hugo/'

[languages]
[languages.es]
title = "Web de Iv치n"
weight = 1
languageName = "Espa침ol"

title = 'Mi web de practicas'
theme = "relearn"

defaultContentLanguage="es"
[Languages]
[Languages.es]

landingPageName = "<i class='fas fa-home'></i> Inicio"

[params]
  themeVariant = "blue"
    description = "Web de practicas de Iv치n Molina sobre Markdown"
  # Shows a checkmark for visited pages on the menu
[menu]
  [[menu.main]]
    identifier = "tema1"
    name = "Tema 1"
    url = "/tema1/"
    
    [[menu.main]]
    identifier = "Sobre mi"
    name = "Sobre mi"
    url = "/about"


[[menu.shortcuts]]
name="<i class='fab fa-js-square'></i>  Lenguaje JavaScript"
identified=""
url="https://developer.mozilla.org/es/docs/Web/JavaScript"
weight=1

[[menu.shortcuts]]
name=" <i class='fab fa-wikipedia-w'></i>  Wikipedia"
identified=""
url="https://es.wikipedia.com"
weight=2

[[menu.shortcuts]]
name="<i class='fab fa-markdown'></i>   M치s info Markdown"
identified=""
url="https://markdown.es/"
weight=3

[[menu.shortcuts]]
name="<i class='fab fa-internet-explorer'></i>   Web oficial de Hugo"
identified=""
url="https://gohugo.io/"
weight=4

